name: Update Cache
on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 7 am UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger cache update
        run: |
          curl -X GET "https://papers.takara.ai/api/update-cache" \
            -H "X-Update-Key: ${{ secrets.UPDATE_KEY }}" --fail
